apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nft1
  name: nft1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nft1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nft1
    spec:
      containers:
      - image: shishirkhandelwal/nft-create-solana:7
        name: nft
        command: ["/bin/bash","-c","npm run-script start"]
        resources: {}
status: {}
